### ISSUE TITLE
给Part显示的时候分组（boss显示中）

### ISSUE THREAD

**Issue by xcluo** [thstack/bug-report#101]
现在part多了，在boss展示中有点乱。

分组依赖两个字段：
    1. tag
    2. parent  （还没上传 allspark)

第一个字段相当于 组名，  第二个子段时 给组内的所有 Part 排列顺序。

**Comment by hajifish** [comment]
@almasgeek  协助 @Vincent 完成。

**Comment by CodeAlmas** [comment]
Okay

**Comment by hajifish** [comment]
到底是 按照 tag 还是 tech 需要根据用户反馈修改，暂不开发。
