### ISSUE TITLE
分工looker各主要功能的负责人

### ISSUE THREAD

**Issue by xcluo** [THSTACK/bug-report#112]
想起一块，安排个人做，最后完成的项目就管理上比较混乱，在用户出现问题的时候， 可能需要多个人协作，或者找不到协作的人去处理之前的bug.

把looker按照主要的功能分给不同的人负责，一旦出现问题，可直接处理。

比如：
      按照核心功能，辅助功能，

     或者：

           学习功能，用户功能

。。。。。。。。。。。。。。。。。。。。。。。

**Comment by hajifish** [comment]
Done
