### ISSUE TITLE
更新学习记录，按照百分比判断，而不是最后一个task

### ISSUE THREAD

**Issue by xcluo** [thstack/bug-report#123]
完成当前stage，但没有学习下一个就退出了，这时候需要记录下一个stage，使得用户能下次在start直接进入下一个stage.  这个功能基本完成了，但是：

        必须是在当前stage的最后一个task学习的时候才能触发，需要调整为：

        在stage学习完成课程/Part要求的百分比的时候就触发而不是最后一个task的got it的时候触发。

**Comment by hajifish** [comment]
Done
