### ISSUE TITLE
Opera 28.0 Looker Study 完成的 Stage 无法显示对号

### ISSUE THREAD

**Issue by longgeek** [THSTACK/bug-report#131]
![image](https://cloud.githubusercontent.com/assets/2102615/6817432/34b55518-d2db-11e4-8ea7-bcc1d8b9281a.png)

**Comment by hajifish** [comment]
试试， 找找。

**Comment by hajifish** [comment]
almas 尝试解决下。

**Comment by hajifish** [comment]
@almasgeek  ？？？   收到回复

**Comment by hajifish** [comment]
移动到下一周again.
