### ISSUE TITLE
[Looker] 找回密码

### ISSUE THREAD

**Issue by xcluo** [THSTACK/bug-report#15]
通过邮件找回

**Comment by xcluo** [comment]
需要开发者阐述下设计。

**Comment by longgeek** [comment]
@cooladam201212 ???

**Comment by cooladam201212** [comment]
1. 用户点击忘记密码，页面跳转至输入登陆邮箱
2. 输入的地址为合法格式则提交至后台(前台判断邮箱格式合法性)
3. 后台查询是否存在此账户，存在则生成随机链接发送给用户邮箱提示重新设置密码，不存在则提示用户重新输入；随机链接采用用户名+时间戳hash生成，设定有效时间为24小时存入memcache或redis
4. 有效时间内，用户重新设置密码后删除memcache或redis缓存值；用户未点击链接则链接自动失效

**Comment by xcluo** [comment]
Well Done.

在 2015年1月4日 下午8:00，cooladam201212 <notifications@github.com>写道：

**Comment by xcluo** [comment]
Done?  Commit Again....... quickly.....
