### ISSUE TITLE
[Looker] Group 扩展 （Boss设计成独立组）

### ISSUE THREAD

**Issue by xcluo** [thstack/bug-report#16]
Group扩展字段：  frazy 纪录

**Comment by hajifish** [comment]
Boss 还是设计为独立的， 自定义的  group， 不使用 django的， 我们自己修改的字段太多了，也用不到django permission ，所以没必要，自己定义吧。

涉及到 boss 验证的修改。

**Comment by hajifish** [comment]
Done in version 3.0 by SQLAlchemy ORM.
