### ISSUE TITLE
 [Docker Cluster] 迁移数据库到ROM  (先迁移到sqlarchmey试试，顺带为allspark迁移到sqlarchemy准备）

### ISSUE THREAD

**Issue by xcluo** [thstack/bug-report#19]
可能需要创建新的项目，类似于  allspark

**Comment by hajifish** [comment]
可以开始了， 先迁移到sqlarchmey试试，顺带为allspark迁移到sqlarchemy准备

**Comment by cooladam201212** [comment]
sqlalchemy有一个automap功能，可以映射django的model进行操作

**Comment by vincenthe11** [comment]
啥时候开始做迁移？

**Comment by longgeek** [comment]
上线之前。: )

**Comment by hajifish** [comment]
Allspark translate into sql-alchemy mechanism done.
