### ISSUE TITLE
[Looker][Telphone_pole][Docker]   用户名, docker  container name 验证问题 @frazy

### ISSUE THREAD

**Issue by xcluo** [THSTACK/bug-report#44]
用户创建的虚拟机命名包含username,   username 是在looker注册的， 

是否需要统一 looker 注册用户的  正则  和 Docker Cluster这边的一致？
如果不一致，创建虚拟机的时候过不去，比如 username  包含 "+"

@Longgeek  # Docker #
@Frazy  # Looker Register #

**Comment by longgeek** [comment]
looker 注册的用户名不能包含特殊字符就行了。
