### ISSUE TITLE
[Looker] Looker cache支持

### ISSUE THREAD

**Issue by xcluo** [thstack/bug-report#80]

**Comment by hajifish** [comment]
(需要更换session的MC的Json问题，也就是不能修改 Django源码) @xcluo      ------------ 已经解决。

现在可用 cache了，  开始设计下 cache . 注意：

study/message 等页面不能cache.

index 页面课程部分可以cache，但是 进行中/完成的  需要控制延迟的时间。

主要问题是：
    各种不同的 cache 需求，结合django技术，完成对 looker 各个不同界面的 cache 设计。

**Comment by hajifish** [comment]
Done, 使用MYSQL做初步缓存，MC现在也可以通过打开中间件的方式支持，但需要考虑有些实时的界面。 @baoyiluo
